apiVersion: gateway.networking.k8s.io/v1alpha2
kind: HTTPRoute
metadata:
  name: hydra-client-ui-route
  namespace: { { .Values.client.namespace } }
  annotations:
    external-dns.alpha.kubernetes.io/hostname: "{{ .Values.dns.clientHostname }}" # Client UI DNS hostname
spec:
  parentRefs:
    - name: client-gateway # change to gateway-client-ui
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: "/oauth2/callback" # OAuth2 callback path
      backendRefs:
        - name: hydra-client-service
          port: 443
