# admin-route.yaml
apiVersion: gateway.networking.k8s.io/v1alpha2
kind: HTTPRoute
metadata:
  name: admin-route
  namespace: hydra
  annotations:
    external-dns.alpha.kubernetes.io/hostname: "{{ .Values.dns.adminHostname }}" # Admin UI DNS hostname
spec:
  parentRefs:
    - name: admin-gateway
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: "/admin"
      backendRefs:
        - name: hydra-admin-service
          port: 443
