apiVersion: gateway.networking.k8s.io/v1alpha2
kind: Gateway
metadata:
  name: gateway-client-ui
  namespace: { { .Values.nginx.namespace } }
  annotations:
    external-dns.alpha.kubernetes.io/hostname: "{{ .Values.dns.hydraClientHostname }}" # HydraClient UI DNS hostname
    external-dns.alpha.kubernetes.io/ttl: "{{ .Values.dns.ttl }}" # Optional: DNS TTL value
spec:
  gatewayClassName: nginx
  listeners:
    - protocol: HTTPS
      port: 443
      tls:
        certificateRef:
          name: { { .Values.tls.clientCertName } }
          group: cert-manager.io
          kind: Certificate
      routes:
        kind: HTTPRoute
        selector:
          matchLabels:
            app: hydra-client
