apiVersion: v1
kind: ConfigMap
metadata:
  name: vault-k8s-auth-config
  namespace: { { .Values.vault.namespace } }
data:
  k8sAuthArgs: |
    args:
      - kubernetes_host="https://$(KUBERNETES_PORT_443_TCP_ADDR):443"
      - kubernetes_ca_cert=@/var/run/secrets/kubernetes.io/serviceaccount/ca.crt
      - token_reviewer_jwt=$(cat /var/run/secrets/kubernetes.io/serviceaccount/token)
